# Generated by Django 3.0.8 on 2020-07-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='BandName',
        ),
        migrations.DeleteModel(
            name='BandSummary',
        ),
    ]
