# Generated by Django 3.0.8 on 2021-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profiles', '0005_bandprofile_bandimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandprofile',
            name='bandImage',
            field=models.ImageField(upload_to='staticfiles/'),
        ),
    ]
