# Generated by Django 3.0.8 on 2021-12-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profiles', '0006_auto_20211214_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandprofile',
            name='bandImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
